PYTHONPATH=. python scripts/mp_wrapper.py \
    --script scripts/run_grip.py \
    --num_process 8 \
    --dataset clegr_reasoning \
    --output_file clegr_reasoning_qwen_context_submit.json \
    --num_test 400 \
    --do_eval \
    --metrics em f1 hit llm \
    --llm_as_judge_model qwen-32b \
    --report_to_wandb \
    --wandb_project_name grip \
    --wandb_run_name clegr_reasoning_qwen_context_submit \
    --subprocess_args \
    --overwrite False \
    --task_generator_model_name qwen-7b \
    --num_context_qa 20 \
    --num_reason_qa 160 \
    --num_summarization 20 \
    --task_gen_max_length 1000 \
    --tokenize_max_length 4096 \
    --gen_max_length 1000 \
    --model_name qwen-7b \
    --quantization False \
    --lora_r 16 \
    --lora_alpha 32 \
    --target_modules down_proj up_proj gate_proj \
    --gather_batches True \
    --num_train_epochs 50 \
    --involve_qa_epochs 50 \
    --s1_stop_loss_threshold 0.4 \
    --s2_stop_loss_threshold 0.4 \
    --s1_min_epoch 5 \
    --s2_min_epoch 5 \
    --continue_training False \
    --remove_unused_columns True \
    --report_to none \
    --overwrite_output_dir True \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 128 \
    --learning_rate 1e-3 \
    --weight_decay 1e-4 \
    --adam_beta1 0.9 \
    --adam_beta2 0.98 \
    --adam_epsilon 1e-8 \
    --max_grad_norm 1.0 \
    --log_level info \
    --logging_strategy steps \
    --logging_steps 1 \
    --save_strategy no \
    --bf16 True \
    --tf32 False \
    --gradient_checkpointing False \
    --lr_scheduler_type linear \
    --no_graph_context False \
    --use_subgraph False \
    --index_format False

